from config.settings import settings

BASE_DIR = settings.STORAGE_DIR.parent

STORAGE_DIR = settings.STORAGE_DIR

FACE_STORAGE_DIR = settings.FACE_STORAGE_DIR
FACE_MODELS_DIR = settings.FACE_MODELS_DIR
FACE_ONNX_PATH = settings.FACE_ONNX_PATH

ENERGY_STORAGE_DIR = settings.ENERGY_STORAGE_DIR
ENERGY_DATASETS_DIR = settings.ENERGY_DATASETS_DIR
ENERGY_MODELS_DIR = settings.ENERGY_MODELS_DIR

ENERGY_MODEL_PATH = settings.ENERGY_MODEL_PATH
ENERGY_FEATURES_PATH = settings.ENERGY_FEATURES_PATH

SIM_THRESHOLD = settings.SIM_THRESHOLD
ADMIN_TOKEN = settings.ADMIN_TOKEN

KNOWN_COOLDOWN_SEC = settings.KNOWN_COOLDOWN_SEC
UNKNOWN_COOLDOWN_SEC = settings.UNKNOWN_COOLDOWN_SEC
UNKNOWN_CONFIRM_COUNT = settings.UNKNOWN_CONFIRM_COUNT