name: smart_home_app
description: "A premium Smart Home Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  flutter_iconly: ^1.0.2
  lucide_icons: ^0.257.0
  flutter_localizations:
    sdk: flutter
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  camera: ^0.11.0+2
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.2.2
  local_auth: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/edge_logo.png"

flutter_native_splash:
  color: "#0F1A2C"
  android: true
  ios: true
  android_12:
    color: "#0F1A2C"

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
  
#   fonts:
#     - family: DIN Next Arabic
#       fonts:
#         - asset: assets/fonts/DINNextLTArabic-Regular.ttf
#         - asset: assets/fonts/DINNextLTArabic-Bold.ttf
#           weight: 700
